name: mental-health-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - imbalanced-learn
  - tensorflow
  - keras
  - flask
  - streamlit
  - joblib
